# Generated by Django 3.2.9 on 2022-06-18 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('Informacion', 'info'), ('Cancelacion', 'cancelacion'), ('Confirmacion', 'confirmacion'), ('Reasignacion', 'reasignacion')], default='Informacion', max_length=20)),
                ('verbo', models.CharField(max_length=220)),
                ('tiempo', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
                ('mensaje', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificiaciones',
                'db_table': 'notificaciones',
                'abstract': False,
            },
        ),
    ]
