# Generated by Django 3.2.9 on 2022-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='direct',
            field=models.URLField(blank=True, null=True),
        ),
    ]
