# Generated by Django 3.2.9 on 2022-06-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Notificaciones', '0002_notificacion_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='actor_conten_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='object_id_actor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
