# Generated by Django 3.2.9 on 2022-06-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0002_notificacion_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='nivel',
        ),
    ]
