# Generated by Django 3.2.9 on 2022-06-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0003_auto_20220618_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='actor_conten_type',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='object_id_actor',
        ),
    ]
