# Generated by Django 3.2.9 on 2022-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0003_remove_notificacion_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='direct',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
