# Generated by Django 3.2.9 on 2022-06-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_post'),
        ('Notificaciones', '0004_auto_20220618_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Usuarios.usuario'),
        ),
    ]
