# Generated by Django 3.2.9 on 2022-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
