# Generated by Django 3.2.9 on 2022-05-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total_pagar',
            field=models.IntegerField(default=0, verbose_name='Total a pagar'),
        ),
    ]
