# Generated by Django 3.2.9 on 2022-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_cita_horafincita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horaFinCita',
            field=models.TimeField(blank=True, null=True, verbose_name='Fecha de Fin de la Cita'),
        ),
    ]
