# Generated by Django 3.2.9 on 2022-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_cita_horafincita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='horaFin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
