# Generated by Django 3.2.9 on 2022-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20220329_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_pagar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total a pagar'),
        ),
        migrations.DeleteModel(
            name='Pedido_Personalizado',
        ),
    ]
