# Generated by Django 3.2.9 on 2022-06-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('Empleado', 'Es un empleado'), ('Cliente', 'Es un cliente'), ('Administrador', 'Es un administrador'), ('Grado 1', 'Puede visualizar elementos de grado 1'), ('Grado 2', 'Puede visualizar elementos de grado 2'), ('Grado 3', 'Puede visualizar elementos de grado 3'), ('Grado 4', 'Puede visualizar elementos de grado 4'), ('Grado 5', 'Puede visualizar elementos de grado 5'), ('Grado 6', 'Puede visualizar elementos de grado 6'), ('Grado 7', 'Puede visualizar elementos de grado 7'), ('Grado 8', 'Puede visualizar elementos de grado 8'), ('Grado 9', 'Puede visualizar elementos de grado 9'), ('Grado 10', 'Puede visualizar elementos de grado 10')]},
        ),
    ]
