# Generated by Django 3.2.9 on 2022-05-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cod_postal', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Codigo_Postal',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número De Celular'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cod_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.codigopostal'),
        ),
    ]
