# Generated by Django 3.2.9 on 2022-03-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['id_compras'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
    ]
