# Generated by Django 3.2.9 on 2022-06-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='descripcion',
        ),
    ]
