# Generated by Django 3.2.9 on 2022-06-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0002_historialcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompra',
            name='compra_id',
            field=models.ForeignKey(blank=True, db_column='id_compras', default=1, on_delete=django.db.models.deletion.CASCADE, to='Modulo_compras.compra', verbose_name='Compra'),
            preserve_default=False,
        ),
    ]
