# Generated by Django 3.2.9 on 2022-06-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0002_remove_proveedor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
