# Generated by Django 3.2.9 on 2022-03-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0002_auto_20220328_0627'),
        ('Modulo_compras', '0002_auto_20220328_0638'),
    ]

    operations = [
    ]
