# Generated by Django 3.2.9 on 2022-06-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0003_historialcompra_compra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompra',
            name='producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
