# Generated by Django 3.2.9 on 2022-06-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0004_historialcompra_producto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialcompra',
            table='Historial_Compra',
        ),
    ]
