# Generated by Django 3.2.9 on 2022-06-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0005_alter_historialcompra_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompra',
            name='compra_id',
        ),
        migrations.AddField(
            model_name='historialcompra',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo_compras.compra'),
        ),
    ]
