# Generated by Django 3.2.9 on 2022-06-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_compras', '0006_auto_20220608_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo_compras.producto'),
        ),
    ]
